"""Generate src/bitvavo_sdk/_async_endpoints.py from _endpoints.py.

Usage:
    python scripts/generate_async.py          # rewrite the file
    python scripts/generate_async.py --check  # exit 1 if it is out of date (CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent / "src" / "bitvavo_sdk"
SRC = PKG / "_endpoints.py"
DST = PKG / "_async_endpoints.py"

HEADER = '''"""Async twin of ``_endpoints.py``.

GENERATED by scripts/generate_async.py. Do not edit by hand.
"""
'''


def _replace_once(text: str, old: str, new: str) -> str:
    if old not in text:
        raise SystemExit(f"generate_async: expected to find {old!r} in {SRC.name}")
    return text.replace(old, new, 1)


def transform(source: str) -> str:
    # Swap the module docstring for the generated-file header.
    end = source.index('"""', 3) + 3
    text = HEADER + source[end:].lstrip("\n").join(["\n", ""])
    text = _replace_once(
        text,
        "from typing import Any, Collection, Dict, Iterator, List, Optional, cast",
        "from typing import Any, AsyncIterator, Collection, Dict, List, Optional, cast",
    )
    text = _replace_once(text, "\nimport time\n", "\nimport asyncio\nimport time\n")
    text = _replace_once(text, "class SyncEndpoints(", "class AsyncEndpoints(")
    # Blocking sleeps would stall the event loop.
    text = text.replace("time.sleep(", "await asyncio.sleep(")
    text = re.sub(r"\bIterator\[", "AsyncIterator[", text)
    # Methods (indented defs) become coroutines; module-level helpers stay sync.
    text = re.sub(r"^( +)def ", r"\1async def ", text, flags=re.M)
    # Every call to the transport or to another endpoint method must be awaited.
    text = re.sub(r"(?<!await )self\.(_call|[a-z]\w*)\(", r"await self.\1(", text)
    return text


def main() -> int:
    generated = transform(SRC.read_text())
    if "--check" in sys.argv:
        if not DST.exists() or DST.read_text() != generated:
            print(f"{DST.name} is out of date; run scripts/generate_async.py")
            return 1
        return 0
    DST.write_text(generated)
    print(f"wrote {DST.relative_to(PKG.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
